"""add user fks to tasks and team_members

Revision ID: 7a8828cc59d1
Revises: c65cb1c82877
Create Date: 2026-08-17 21:06:39.654631

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8828cc59d1"
down_revision: str | Sequence[str] | None = "c65cb1c82877"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("created_by_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        "fk_tasks_created_by_id_users", "tasks", "users", ["created_by_id"], ["id"]
    )
    op.add_column("team_members", sa.Column("user_id", sa.Uuid(), nullable=True))
    op.create_unique_constraint("uq_team_members_user_id", "team_members", ["user_id"])
    op.create_foreign_key(
        "fk_team_members_user_id_users", "team_members", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_team_members_user_id_users", "team_members", type_="foreignkey"
    )
    op.drop_constraint("uq_team_members_user_id", "team_members", type_="unique")
    op.drop_column("team_members", "user_id")
    op.drop_constraint("fk_tasks_created_by_id_users", "tasks", type_="foreignkey")
    op.drop_column("tasks", "created_by_id")
    # ### end Alembic commands ###
