"""create team_memebers teasks task_dependencies

Revision ID: ad878abd3458
Revises:
Create Date: 2026-08-09 12:31:16.325421

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ad878abd3458"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_members",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "skills",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sprint_id", sa.Uuid(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("backlog", "todo", "doing", "done", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("assignee_id", sa.Uuid(), nullable=True),
        sa.Column("story_points", sa.Integer(), nullable=True),
        sa.Column("risk_flag", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["team_members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_dependencies",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("from_task_id", sa.Uuid(), nullable=False),
        sa.Column("to_task_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "from_task_id <> to_task_id", name="ck_task_dependency_no_self_reference"
        ),
        sa.ForeignKeyConstraint(
            ["from_task_id"],
            ["tasks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_task_id"],
            ["tasks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_task_id", "to_task_id", name="uq_task_dependency_edge"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_dependencies")
    op.drop_table("tasks")
    op.drop_table("team_members")
    op.execute("DROP TYPE IF EXISTS taskstatus")
    # ### end Alembic commands ###
