"""add projects table

Revision ID: c9829c64b429
Revises: d1193018e09d
Create Date: 2026-08-31 19:56:41.086611

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9829c64b429"
down_revision: str | Sequence[str] | None = "d1193018e09d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("requirements", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("duration_weeks", sa.Integer(), nullable=False),
        sa.Column("sprint_length_weeks", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "planning", "active", "completed", "cancelled", name="projectstatus"
            ),
            nullable=False,
        ),
        sa.Column("ai_opinion", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("projects")
    op.execute("DROP TYPE IF EXISTS projectstatus")
    # ### end Alembic commands ###
