"""Pydantic schemas for comments."""

from datetime import datetime
from typing import Any
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, field_validator


class CommentCreate(BaseModel):
    """Pydantic schema for creating a comment."""

    task_id: UUID = Field(description="The id of the task the comment is for.")
    body: str = Field(description="The body of the comment.", min_length=1)


class CommentRead(BaseModel):
    """Pydantic schema for reading a comment."""

    model_config = ConfigDict(from_attributes=True)

    id: UUID = Field(description="The id of the comment.")
    task_id: UUID = Field(
        description="The id of the task on which the comment is posted."
    )
    body: str = Field(description="The body of the comment.")
    user_id: UUID | None = Field(
        description="The id of the user who posted the comment.", default=None
    )
    is_ai: bool = Field(description="Whether the comment was generated by AI.")
    created_at: datetime = Field(
        description="The timestamp when the comment was created."
    )
    updated_at: datetime = Field(
        description="The timestamp when the comment was edited"
    )


class CommentUpdate(BaseModel):
    """Pydantic schema for updating a comment."""

    body: str | None = Field(
        description="The body of the comment to update.", default=None, min_length=1
    )

    @field_validator("body", mode="before")
    @classmethod
    def reject_null(cls, value: Any) -> Any:
        """Reject null values for the body field."""
        if value is None:
            raise ValueError(
                "Null is not allowed, omit the field to leave it unchanged."
            )
        return value
